server:
  port: 80
spring:
  application:
    name: faber-admin-dev
  profiles:
    active: dev
  web:
    resources:
      static-locations: classpath:public/,classpath:static/,file:static/,file:public/,classpath:/resources,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      name: faber-admin
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DBNAME:faber_admin}?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8&useSSL=false
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:123456}
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin@1234

  # spring boot admin client
#  boot:
#    admin:
#      client:
#        url: http://localhost:8001
#        username: admin
#        password: 103Tiger
#        instance:
#          service-base-url: http://localhost

  #redis-cache 相关，这里是springboot2.x的redis配置，与下面ace-cache的配置重复，但是都不能删除，后续要改进
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: 0
    timeout: 2000
    password: 'admin@elec#1234'
    sysName: faber-admin #默认key前缀
    enable: true #是否启用ace-cache
    userkey: #用户会话的标志，存放于cookie或request header
    lettuce:
      pool:
        max-active: 300
        min-idle: 100
        max-wait: 1000
  servlet:
    multipart:
      max-file-size: 50MB
#      location: /tmp

mybatis:
  base-packages: com.faber.**.mapper
  mapper-locations: "classpath*:mapper/**/*.xml"
  configuration:
    map-underscore-to-camel-case: true

# 配置swagger
swagger:
  enabled: true
  base-package: com.faber
  title: kgcesi-admin
  version: 1.0.0.SNAPSHOTProcessDiagramGenerator
  description: 管理后端服务
  contact:
    name: admin

# Client Auth
faber:
  auth:
    jwt:
      pri: faber-admin:AUTH:JWT:PRI
      pub: faber-admin:AUTH:JWT:PUB

management:
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: ./log/springboot.admin.log
  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  token-header: Authorization
  expire: 864000
  rsa-secret: xx1WET12^%3^(WE45

# Qiniu
# 存储区域：https://developer.qiniu.com/kodo/1671/region-endpoint-fq
qiniu:
  accessKey: xxx
  secretKey: xxx
  bucket: faber-admin
  host: http://faber.admin.file.dward.cn
  # 这里是增加一层路径，用于区分
  prefix: faber-admin

# 一些默认配置
default:
  setting:
    # 高德地图SDK
    amap:
      key: xx
    # 加密，aes秘钥长度必须为16位
    aes:
      key: 2345ASDC89ABCSEQ
      salt: DYgaREIsYrj24QxN

#============================================================================
# netty socket io setting
#============================================================================
# host在本地测试可以设置为localhost或者本机IP，在Linux服务器跑可换成服务器IP
socketio:
  host: 127.0.0.1
  port: 8081
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000

# --------------------------------------------- 短信模板-阿里云 ---------------------------------------------
aliyun:
  sms:
    regionId: cn-hangzhou
    accessKeyId: xx
    secret: xx
    signName: xx
    # 短信模板配置
    smsConfig:
      # 短信验证码
      SMD_CODE:
        smsCode: SMS_xxx
        template: '您的验证码为：${code}，该验证码5分钟内有效，请勿泄露于他人。'
        keys:
          - code
